apiVersion: v2
name: kube-prometheus-stack
version: 0.1.0
type: application

dependencies:
  - name: kube-prometheus-stack
    version: 80.6.0
    repository: https://prometheus-community.github.io/helm-charts
