apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage.fullname" . }}
type: Opaque
data:
{{- if .Values.garage.rpcSecret }}
  rpc_secret: {{ .Values.garage.rpcSecret | b64enc }}
{{- else }}
  rpc_secret: {{ randAlphaNum 32 | b64enc }}
{{- end }}

