apiVersion: v1
kind: Service
metadata:
  name: {{ include "garage.fullname" . }}-headless
  labels:
    {{- include "garage.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 3900
      name: s3-api
    - port: 3901
      name: rpc
    - port: 3902
      name: s3-web
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}

